### ISSUE TITLE
cfntagger fails when running with empty CFN_TAGS envvar

### ISSUE THREAD

**Issue by kristofwillen** [kristofwillen/cfntagger#6]
I'm running cfntagger with an empty config, as I only want to add the git tags.  Doing so, cfntagger fails with an UnboundLocalError:

```bash
$ export CFN_TAGS='{}'
$ cfntagger -f ./template.yaml -s -g
[./template.yaml][Resource] CheckovStats => AWS::Serverless::Function
[./template.yaml][Resource] CheckovLogGroup => AWS::Logs::LogGroup

Traceback (most recent call last):
  File "/usr/local/bin/cfntagger", line 65, in <module>
    cfn_tagger.tag()
  File "/usr/local/lib/python3.10/site-packages/cfntagger/cfntagger.py", line 401, in tag
    self.resources[item]["Properties"]["Tags"] = [addtags]
UnboundLocalError: local variable 'addtags' referenced before assignment
```

**Comment by kristofwillen** [comment]
Fixed in 0.9.7
